name: pypi-upload
on:
  push:
    tags: ['v[0-9]+\.[0-9]+\.[0-9]+[ab]?']
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install build package
      run: pip install build

    - name: Build
      run: python -m build

    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
